Admin/Controllers/SystemRoleController.cs
using Admin.DTOs;
using Admin.Services;
using Admin.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Admin.Controllers
{
    public class SystemRoleController : Controller
    {
        private ISystemRoleService _systemRoleService;
        public SystemRoleController()
        {
            this._systemRoleService = new SystemRoleService();
        }

        // GET: SystemAdministration
        public ActionResult Index()
        {
            return View();
        }

        [Login]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(RoleDTO Dto)
        {
            var result = _systemRoleService.Create(Dto);
            if (result == true) return RedirectToAction("GetAllUser");
            return View();
        }

        [Login]
        public ActionResult GetAll()
        {
            var result = _systemRoleService.GetAll();
            return View(result);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var result = _systemRoleService.DeleteById(id);
            if (result == true)
                return RedirectToAction("GetAllUser");
            else
                return View(result);
        }

        [Login]
        public ActionResult Detail(int id)
        {
            var result = _systemRoleService.GetDTOById(id);
            return View(result);
        }

        [HttpPost]
        public ActionResult Update(RoleDTO Dto)
        {
            var result = _systemRoleService.Update(Dto);
            if (result == true)
                return RedirectToAction("GetAllUser");
            else
                return View(result);
        }
    }
}

Admin/Views/SystemRole/Create.cshtml
@model Admin.DTOs.RoleDTO
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Create", "SystemRole", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2>Người dùng</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="~/admin">Dashboard</a>
                </li>
                <li class="breadcrumb-item">
                    <a>Role</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Create</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-3">
            <br />
            <button id="BtnCreate" class="btn btn-success " type="submit"><i class="fa fa-upload"></i>&nbsp;&nbsp;<span class="bold">Thêm mới</span></button>
            <a class="btn btn-danger " href="@Url.Action("GetAll","SystemRole")"><i class="fa fa-undo"></i>&nbsp;&nbsp;<span class="bold">Trở về</span></a>

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <p><i class="text-danger"><strong>* </strong>Các mục đánh dấu (*) là bắt buộc</i></p>

                    </div>
                    <div class="ibox-content">
                        <form method="get" id="formCreateAccount">
                            <div class="row">
                                <div class="col-md-12">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="form-group">
                                        @Html.Label("Tên quyền", htmlAttributes: new { @class = "control-label col-12" })
                                        <div class="">

                                            @Html.EditorFor(m => m.RoleName, new { htmlAttributes = new { @class = "form-control", @required = "required", placeholder = "Tên Quyền" } })
                                            @Html.ValidationMessageFor(m => m.RoleName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                   
                                </div>
                               
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

}

Admin/Views/SystemRole/GetAll.cshtml
@model IEnumerable<Admin.Models.Role>
@{
    ViewBag.Title = "ListRolePage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>Danh sách Quyền hệ thống</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="~/admin">Dashboard</a>
            </li>
            <li class="breadcrumb-item">
                <a>Role</a>
            </li>
            <li class="breadcrumb-item active">
                <strong>ListUserPage</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-3">
        <br />
        <a class="btn btn-success " href="@Url.Action("Create","SystemRole")"><i class="fa fa-upload"></i>&nbsp;&nbsp;<span class="bold">Thêm mới</span></a>
        <a class="btn btn-danger" href="#"><i class="fa fa-trash"></i>&nbsp;&nbsp;<span class="bold">Thùng rác(@ViewBag.demrac)</span></a>

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">

                <div class="ibox-content">

                    <table class="footable table table-stripped toggle-arrow-tiny">
                        <thead>
                            <tr>
                                <th data-toggle="true">STT</th>
                                <th>Tên Quyền</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.RoleId</td>

                                    <td>
                                        <a href="@Url.Action("UserDetail","User", new {Id = item.RoleId })">@item.RoleName</a>
                                    </td>
                                    
                                    <td>
                                        <button type="button" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Chỉnh sửa">
                                            <a href="@Url.Action("Update", "User", new { id = item.RoleId })" class="text-white"><i class="fa fa-edit"></i></a>
                                        </button>
                                        <button type="button" class="btn btn-danger" data-toggle="tooltip" data-placement="top" title="Xóa">
                                            <a href="@Url.Action("Delete", "User", new { id = item.RoleId })" class="text-white"><i class="fa fa-trash"></i></a>
                                        </button>
                                    </td>
                                </tr>
                              
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="5">
                                    <ul class="pagination float-right"></ul>
                                </td>
                            </tr>
                        </tfoot>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>

Admin/Views/SystemRole/Update.cshtml
@model Admin.DTOs.RoleDTO

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Update", "SystemRole", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2>Quản trị viên</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="~/admin">Dashboard</a>
                </li>
                <li class="breadcrumb-item">
                    <a>Role</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Update</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-3">
            <br />
            <button class="btn btn-success " type="submit"><i class="fa fa-upload"></i>&nbsp;&nbsp;<span class="bold">Update</span></button>
            <a class="btn btn-danger " href="@Url.Action("GetAll","SystemRole")"><i class="fa fa-undo"></i>&nbsp;&nbsp;<span class="bold">Trở về</span></a>

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <p><i class="text-danger"><strong>* </strong>Các mục đánh dấu (*) là bắt buộc</i></p>

                    </div>
                    <div class="ibox-content">
                        <form method="get">
                            <div class="row">
                                <div class="col-md-9">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.Id)
                                    <div class="form-group">
                                        <label>Tên Quyền</label>
                                        @Html.EditorFor(model => model.RoleName, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                        @Html.ValidationMessageFor(model => model.RoleName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

}